### ISSUE TITLE
xyzt_units info missing in image?

### ISSUE THREAD

**Issue by KXCY-AI** [black0017/ct-intensity-segmentation#1]
According to the article, `pixdim` should be caculated in by the unit **mm**, which means the `xyzt_units`  in Nifti1Header should be **2**.  But I got `xyzt_units      : 0` in the images. 

Wondering if the xyzt_units info is lost in the image? 

BTW, thanks for the great tutorial.

**Comment by black0017** [comment]
At which images are you referring to?
You were right on the units according to: https://brainder.org/2012/09/23/the-nifti-file-format/

`Both spatial and temporal measurement units, used for the dimensions dim[1] to dim[4] (and, respectively, for pixdim[]), are encoded in the field char xyzt_units. The bits 1-3 are used to store the spatial dimensions, the bits 4-6 are for temporal dimensions, and the bits 6 and 7 are not used. A temporal offset can be specified in the field float toffset. The codes for xyzt_units, in decimal, are:`
![image](https://user-images.githubusercontent.com/13345132/152656895-de8f4829-63f4-46ac-ab51-05b809912040.png)

I assumed mm for this tutorial based on the images I dealt with, but indeed checking the `xyzt_units` would be more appropriate.

Unknown units (code zero 0) is presumably a problem  from the images not from the repo, so i ll close the issue! 
Thanks for the info @KXCY-AI
